export const pilots = [
  {
    id: 1,
    nome: "Lewis Hamilton",
    equipe: "Mercedes",
    pais: "Reino Unido",
    nacionalidade: "Britânico",
    data_nascimento: "1985-01-07",
    numero_carro: 44,
    vitorias_carreira: 100,
    campeonatos_mundiais: 7,
  },
  {
    id: 2,
    nome: "Valtteri Bottas",
    equipe: "Mercedes",
    pais: "Finlândia",
    nacionalidade: "Finlandês",
    data_nascimento: "1989-08-28",
    numero_carro: 77,
    vitorias_carreira: 10,
    campeonatos_mundiais: 0,
  },
  {
    id: 3,
    nome: "Max Verstappen",
    equipe: "Red Bull Racing",
    pais: "Países Baixos",
    nacionalidade: "Holandês",
    data_nascimento: "1997-09-30",
    numero_carro: 33,
    vitorias_carreira: 20,
    campeonatos_mundiais: 0,
  },
  {
    id: 4,
    nome: "Sergio Pérez",
    equipe: "Red Bull Racing",
    pais: "México",
    nacionalidade: "Mexicano",
    data_nascimento: "1990-01-26",
    numero_carro: 11,
    vitorias_carreira: 2,
    campeonatos_mundiais: 0,
  },
  {
    id: 5,
    nome: "Lando Norris",
    equipe: "McLaren",
    pais: "Reino Unido",
    nacionalidade: "Britânico",
    data_nascimento: "1999-11-13",
    numero_carro: 4,
    vitorias_carreira: 0,
    campeonatos_mundiais: 0,
  },
  {
    id: 6,
    nome: "Daniel Ricciardo",
    equipe: "McLaren",
    pais: "Austrália",
    nacionalidade: "Australiano",
    data_nascimento: "1989-07-01",
    numero_carro: 3,
    vitorias_carreira: 7,
    campeonatos_mundiais: 0,
  },
  {
    id: 7,
    nome: "Charles Leclerc",
    equipe: "Ferrari",
    pais: "Mônaco",
    nacionalidade: "Monegasco",
    data_nascimento: "1997-10-16",
    numero_carro: 16,
    vitorias_carreira: 2,
    campeonatos_mundiais: 0,
  },
  {
    id: 8,
    nome: "Carlos Sainz Jr.",
    equipe: "Ferrari",
    pais: "Espanha",
    nacionalidade: "Espanhol",
    data_nascimento: "1994-09-01",
    numero_carro: 55,
    vitorias_carreira: 0,
    campeonatos_mundiais: 0,
  },
  {
    id: 9,
    nome: "Fernando Alonso",
    equipe: "Alpine",
    pais: "Espanha",
    nacionalidade: "Espanhol",
    data_nascimento: "1981-07-29",
    numero_carro: 14,
    vitorias_carreira: 32,
    campeonatos_mundiais: 2,
  },
  {
    id: 10,
    nome: "Esteban Ocon",
    equipe: "Alpine",
    pais: "França",
    nacionalidade: "Francês",
    data_nascimento: "1996-09-17",
    numero_carro: 31,
    vitorias_carreira: 1,
    campeonatos_mundiais: 0,
  },
  {
    id: 11,
    nome: "Sebastian Vettel",
    equipe: "Aston Martin",
    pais: "Alemanha",
    nacionalidade: "Alemão",
    data_nascimento: "1987-07-03",
    numero_carro: 5,
    vitorias_carreira: 53,
    campeonatos_mundiais: 4,
  },
  {
    id: 12,
    nome: "Lance Stroll",
    equipe: "Aston Martin",
    pais: "Canadá",
    nacionalidade: "Canadense",
    data_nascimento: "1998-10-29",
    numero_carro: 18,
    vitorias_carreira: 0,
    campeonatos_mundiais: 0,
  },
  {
    id: 13,
    nome: "Pierre Gasly",
    equipe: "AlphaTauri",
    pais: "França",
    nacionalidade: "Francês",
    data_nascimento: "1996-02-07",
    numero_carro: 10,
    vitorias_carreira: 1,
    campeonatos_mundiais: 0,
  },
  {
    id: 14,
    nome: "Yuki Tsunoda",
    equipe: "AlphaTauri",
    pais: "Japão",
    nacionalidade: "Japonês",
    data_nascimento: "2000-05-11",
    numero_carro: 22,
    vitorias_carreira: 0,
    campeonatos_mundiais: 0,
  },
  {
    id: 15,
    nome: "Kimi Räikkönen",
    equipe: "Alfa Romeo Racing",
    pais: "Finlândia",
    nacionalidade: "Finlandês",
    data_nascimento: "1979-10-17",
    numero_carro: 7,
    vitorias_carreira: 21,
    campeonatos_mundiais: 1,
  },
  {
    id: 16,
    nome: "Antonio Giovinazzi",
    equipe: "Alfa Romeo Racing",
    pais: "Itália",
    nacionalidade: "Italiano",
    data_nascimento: "1993-12-14",
    numero_carro: 99,
    vitorias_carreira: 0,
    campeonatos_mundiais: 0,
  },
  {
    id: 17,
    nome: "Mick Schumacher",
    equipe: "Haas",
    pais: "Alemanha",
    nacionalidade: "Alemão",
    data_nascimento: "1999-03-22",
    numero_carro: 47,
    vitorias_carreira: 0,
    campeonatos_mundiais: 0,
  },
  {
    id: 18,
    nome: "Nikita Mazepin",
    equipe: "Haas",
    pais: "Rússia",
    nacionalidade: "Russo",
    data_nascimento: "1999-03-02",
    numero_carro: 9,
    vitorias_carreira: 0,
    campeonatos_mundiais: 0,
  },
  {
    id: 19,
    nome: "Nicholas Latifi",
    equipe: "Williams",
    pais: "Canadá",
    nacionalidade: "Canadense",
    data_nascimento: "1995-06-29",
    numero_carro: 6,
    vitorias_carreira: 0,
    campeonatos_mundiais: 0,
  },
  {
    id: 20,
    nome: "George Russell",
    equipe: "Williams",
    pais: "Reino Unido",
    nacionalidade: "Britânico",
    data_nascimento: "1998-02-15",
    numero_carro: 63,
    vitorias_carreira: 0,
    campeonatos_mundiais: 0,
  },
];
