export const teams = [
  {
    id: 1,
    nome: "Mercedes",
    pais_sede: "Reino Unido",
    diretor_equipe: "Toto Wolff",
    numero_carros: 2,
    numero_pilotos: 2,
  },
  {
    id: 2,
    nome: "Red Bull Racing",
    pais_sede: "Reino Unido",
    diretor_equipe: "Christian Horner",
    numero_carros: 2,
    numero_pilotos: 2,
  },
  {
    id: 3,
    nome: "McLaren",
    pais_sede: "Reino Unido",
    diretor_equipe: "Zak Brown",
    numero_carros: 2,
    numero_pilotos: 2,
  },
  {
    id: 4,
    nome: "Ferrari",
    pais_sede: "Itália",
    diretor_equipe: "Mattia Binotto",
    numero_carros: 2,
    numero_pilotos: 2,
  },
  {
    id: 5,
    nome: "Alpine",
    pais_sede: "França",
    diretor_equipe: "Laurent Rossi",
    numero_carros: 2,
    numero_pilotos: 2,
  },
  {
    id: 6,
    nome: "Aston Martin",
    pais_sede: "Reino Unido",
    diretor_equipe: "Otmar Szafnauer",
    numero_carros: 2,
    numero_pilotos: 2,
  },
  {
    id: 7,
    nome: "AlphaTauri",
    pais_sede: "Itália",
    diretor_equipe: "Franz Tost",
    numero_carros: 2,
    numero_pilotos: 2,
  },
  {
    id: 8,
    nome: "Alfa Romeo Racing",
    pais_sede: "Suíça",
    diretor_equipe: "Frédéric Vasseur",
    numero_carros: 2,
    numero_pilotos: 2,
  },
  {
    id: 9,
    nome: "Haas",
    pais_sede: "Estados Unidos",
    diretor_equipe: "Günther Steiner",
    numero_carros: 2,
    numero_pilotos: 2,
  },
  {
    id: 10,
    nome: "Williams",
    pais_sede: "Reino Unido",
    diretor_equipe: "Jost Capito",
    numero_carros: 2,
    numero_pilotos: 2,
  },
];
